# -*- coding: utf-8 -*-
"""approach2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skB3CfPt1sk8B6mdul-hY3yzI6EKRcC0
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from google.colab import files

# Parameters for the Schrödinger Equation
L = 10.0  # Spatial domain size
T = 1.0   # Total time
nx = 256  # Number of spatial points
nt = 200  # Number of time steps
hbar = 1.0
m = 1.0
dx = L / (nx - 1)
dt = T / nt

# Initial condition: Gaussian wave packet
x = np.linspace(0, L, nx)
x0 = 5.0  # Center of the Gaussian
sigma = 0.5  # Width of the Gaussian
k0 = 5.0  # Wave number
A = 1.0  # Amplitude

# Initialize wave function
psi = A * np.exp(-(x - x0)**2 / (2 * sigma**2)) * np.exp(1j * k0 * x)
Psi = np.zeros((nt, nx), dtype=complex)
Psi[0, :] = psi

# Time-stepping loop (finite difference method)
for n in range(0, nt - 1):
    for i in range(1, nx - 1):
        Psi[n + 1, i] = Psi[n, i] - (1j * hbar * dt / (2 * m * dx**2)) * (Psi[n, i + 1] - 2 * Psi[n, i] + Psi[n, i - 1])

# Prepare the dataset for training
X = np.zeros((nt * nx, 2))  # [position, time]
Y_real = np.zeros((nt * nx, 1))  # [real part of the wave function]
Y_imag = np.zeros((nt * nx, 1))  # [imaginary part of the wave function]

for n in range(nt):
    for i in range(nx):
        X[n * nx + i, 0] = x[i]          # Position
        X[n * nx + i, 1] = n * dt        # Time
        Y_real[n * nx + i, 0] = np.real(Psi[n, i])  # Real part of the wave function
        Y_imag[n * nx + i, 0] = np.imag(Psi[n, i])  # Imaginary part of the wave function

# Normalize features and labels
X_min, X_max = X.min(axis=0), X.max(axis=0)
X_normalized = (X - X_min) / (X_max - X_min)

Y_real_min, Y_real_max = Y_real.min(), Y_real.max()
Y_real_normalized = (Y_real - Y_real_min) / (Y_real_max - Y_real_min)

Y_imag_min, Y_imag_max = Y_imag.min(), Y_imag.max()
Y_imag_normalized = (Y_imag - Y_imag_min) / (Y_imag_max - Y_imag_min)

# Split the dataset
X_train, X_val, Y_real_train, Y_real_val, Y_imag_train, Y_imag_val = train_test_split(
    X_normalized, Y_real_normalized, Y_imag_normalized, test_size=0.2, random_state=42
)

# Save the dataset
np.savez('schrodinger_dataset.npz', X=X, Y_real=Y_real, Y_imag=Y_imag)
files.download('schrodinger_dataset.npz')

# Define the neural network model with two outputs (Real and Imaginary parts)
model = keras.Sequential([
    layers.Input(shape=(2,)),  # Input layer for [position, time]
    layers.Dense(128, activation='relu', kernel_initializer='he_normal'),  # First hidden layer
    layers.Dense(128, activation='relu', kernel_initializer='he_normal'),  # Second hidden layer
    layers.Dense(64, activation='relu', kernel_initializer='he_normal'),   # Third hidden layer
    layers.Dense(2)  # Output layer with 2 outputs: Real and Imaginary parts
])

# Cosine annealing learning rate scheduler
lr_schedule = tf.keras.optimizers.schedules.CosineDecay(
    initial_learning_rate=0.001, decay_steps=1000, alpha=0.01
)
optimizer = keras.optimizers.Adam(learning_rate=lr_schedule)

# Compile the model
model.compile(optimizer=optimizer, loss='mean_squared_error', metrics=['mae'])

# Train the model
history = model.fit(X_train, np.hstack((Y_real_train, Y_imag_train)), validation_data=(X_val, np.hstack((Y_real_val, Y_imag_val))), epochs=200, batch_size=32)

# Plot training history
plt.figure(figsize=(12, 5))
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.plot(history.history['mae'], label='Train MAE', linestyle='--')
plt.plot(history.history['val_mae'], label='Validation MAE', linestyle='--')
plt.title('Training History')
plt.xlabel('Epochs')
plt.ylabel('Loss / MAE')
plt.legend()
plt.grid()
plt.show()

# Plotting probability density at different time steps
plt.figure(figsize=(12, 6))
for n in range(0, nt, nt // 5):
    plt.plot(x, np.abs(Psi[n, :])**2, label=f'Time = {n * dt:.2f} s')

plt.title('Probability Density over Time')
plt.xlabel('Position')
plt.ylabel('Probability Density')
plt.legend()
plt.grid()
plt.show()

# Save the NN model as .keras format
model.save('nn_model.keras')  # Save as .keras format

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt


# **Define the PINN Model**
class PINN(tf.keras.Model):
    def __init__(self, num_layers=8, num_neurons=256, activation='tanh', dropout_rate=0.1, regularizer=None, **kwargs):
        super(PINN, self).__init__(**kwargs)

        # Default regularizer if None is passed
        if regularizer is None:
            regularizer = tf.keras.regularizers.l2(1e-5)

        # Define the hidden layers
        self.hidden_layers = [
            tf.keras.layers.Dense(
                units=num_neurons,
                activation=activation,
                kernel_regularizer=regularizer
            )
            for _ in range(num_layers)
        ]

        # Define the output layer (2 outputs for Real and Imaginary parts)
        self.output_layer = tf.keras.layers.Dense(
            units=2,  # 2 outputs: Real and Imaginary parts of Psi
            activation=None  # Linear activation for the output
        )

        # Optional dropout
        self.dropout = None
        if dropout_rate > 0:
            self.dropout = tf.keras.layers.Dropout(rate=dropout_rate)

    def call(self, inputs, training=False):
        x = inputs

        # Pass through hidden layers
        for layer in self.hidden_layers:
            x = layer(x)
            if self.dropout:
                x = self.dropout(x, training=training)

        # Output layer
        output = self.output_layer(x)
        return output


# **Loss Function for PINN**
def pinn_loss(model, x, t):
    with tf.GradientTape(persistent=True) as tape:
        tape.watch([x, t])
        inputs = tf.concat([x, t], axis=1)
        psi = model(inputs)
        real, imag = psi[:, 0:1], psi[:, 1:2]

        # Compute derivatives
        psi_t_real = tape.gradient(real, t)
        psi_t_imag = tape.gradient(imag, t)
        psi_x_real = tape.gradient(real, x)
        psi_x_imag = tape.gradient(imag, x)
        psi_xx_real = tape.gradient(psi_x_real, x)
        psi_xx_imag = tape.gradient(psi_x_imag, x)

        # Real and imaginary parts of the physics residual
        residual_real = hbar * psi_t_imag + (hbar**2 / (2 * m)) * psi_xx_real
        residual_imag = -hbar * psi_t_real + (hbar**2 / (2 * m)) * psi_xx_imag

        # Combine residuals
        physics_residual = residual_real**2 + residual_imag**2

    return tf.reduce_mean(physics_residual)


# **Training Loop with Batching**
def train_pinn(model, dataset, optimizer, epochs=500):
    losses = []
    for epoch in range(epochs):
        epoch_loss = 0
        for x_batch, t_batch in dataset:
            with tf.GradientTape() as tape:
                loss = pinn_loss(model, x_batch, t_batch)
            gradients = tape.gradient(loss, model.trainable_variables)
            optimizer.apply_gradients(zip(gradients, model.trainable_variables))
            epoch_loss += loss
        losses.append(epoch_loss / len(dataset))
        if epoch % 10 == 0:
            print(f"Epoch {epoch}, Loss: {epoch_loss / len(dataset)}")
    return losses


# **Plot Training Loss**
def plot_training_loss(losses):
    plt.figure(figsize=(8, 6))
    plt.plot(losses, label="Training Loss", color='blue')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.title('PINN Training Loss over Epochs')
    plt.legend()
    plt.grid(True)
    plt.show()


# **Load Data (Ground Truth)**
try:
    data = np.load('/content/schrodinger_dataset.npz')
    X = data['X']
    Y_real = data['Y_real']
    Y_imag = data['Y_imag']
    Y_real = Y_real.reshape(-1, 1)
    Y_imag = Y_imag.reshape(-1, 1)
    Y = np.hstack([Y_real, Y_imag])
    print("Successfully loaded the ground truth dataset.")
except Exception as e:
    print(f"Error loading ground truth dataset: {e}")


# **Set Hyperparameters**
L, T = 10.0, 1.0
hbar, m = 1.0, 1.0
num_layers = 8
num_neurons = 256
activation = 'tanh'
dropout_rate = 0.1
regularizer = tf.keras.regularizers.l2(1e-5)
epochs = 500


# **Generate Random Training Data**
x_train = tf.random.uniform((1000, 1), 0, L)
t_train = tf.random.uniform((1000, 1), 0, T)


# **Create Dataset and Batch It**
dataset = tf.data.Dataset.from_tensor_slices((x_train, t_train))
dataset = dataset.batch(32).shuffle(1000).prefetch(tf.data.experimental.AUTOTUNE)


# **Initialize the PINN Model**
pinn = PINN(num_layers=num_layers, num_neurons=num_neurons, activation=activation, dropout_rate=dropout_rate, regularizer=regularizer)
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)


# **Train the PINN Model**
losses = train_pinn(pinn, dataset, optimizer, epochs=epochs)


# **Plot the Training Loss**
plot_training_loss(losses)


# **Save the Model**
pinn.save('pinn_model.keras')


# **Make Predictions**
inputs = tf.concat([X[:, 0:1], X[:, 1:2]], axis=1)
pinn_predictions = pinn(inputs)


# **Visualize the Results**
pinn_real = pinn_predictions[:, 0].numpy()
pinn_imag = pinn_predictions[:, 1].numpy()


# **Plot Real Part**
plt.figure(figsize=(10, 6))
plt.plot(X[:, 0], Y_real, label='True Real Part', color='black', linestyle='dashed')
plt.plot(X[:, 0], pinn_real, label='PINN Real Part', color='blue')
plt.xlabel('x')
plt.ylabel('Real(Psi)')
plt.title('Real Part of Psi: Ground Truth vs PINN')
plt.legend()
plt.grid(True)
plt.show()


# **Plot Imaginary Part**
plt.figure(figsize=(10, 6))
plt.plot(X[:, 0], Y_imag, label='True Imaginary Part', color='black', linestyle='dashed')
plt.plot(X[:, 0], pinn_imag, label='PINN Imaginary Part', color='blue')
plt.xlabel('x')
plt.ylabel('Imag(Psi)')
plt.title('Imaginary Part of Psi: Ground Truth vs PINN')
plt.legend()
plt.grid(True)
plt.show()

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Define the PINN model class
class PINN(tf.keras.Model):
    def __init__(self, num_layers=8, num_neurons=256, activation='tanh', dropout_rate=0.1, regularizer=tf.keras.regularizers.l2(1e-5), **kwargs):
        super(PINN, self).__init__(**kwargs)
        self.hidden_layers = [
            tf.keras.layers.Dense(
                num_neurons,
                activation=activation,
                kernel_regularizer=regularizer
            )
            for _ in range(num_layers)
        ]
        self.output_layer = tf.keras.layers.Dense(2)  # Real and Imaginary parts
        self.dropout = tf.keras.layers.Dropout(dropout_rate) if dropout_rate > 0 else None

    def call(self, inputs, training=False):
        x = inputs
        for layer in self.hidden_layers:
            x = layer(x)
            if self.dropout:
                x = self.dropout(x, training=training)
        return self.output_layer(x)

# Load the PINN model
try:
    pinn = tf.keras.models.load_model('/content/pinn_model.keras', custom_objects={'PINN': PINN})
    print("Successfully loaded the PINN model in Keras format.")
except Exception as e:
    print(f"Error loading PINN model: {e}")

# Load the NN model
try:
    nn_model = tf.keras.models.load_model('/content/nn_model.keras')
    print("Successfully loaded the NN model in Keras format.")
except Exception as e:
    print(f"Error loading NN model: {e}")

# Load the ground truth dataset
try:
    data = np.load('/content/schrodinger_dataset.npz')
    X = data['X']  # Features: [x, t]
    Y_real = data['Y_real'].reshape(-1, 1)  # Real part
    Y_imag = data['Y_imag'].reshape(-1, 1)  # Imaginary part
    psi_true = np.hstack([Y_real, Y_imag])  # Combine real and imaginary parts
    print("Successfully loaded the ground truth dataset.")
except Exception as e:
    print(f"Error loading NN dataset: {e}")

# Extract position and time
x_test = X[:, 0].reshape(-1, 1)  # Position
t_test = X[:, 1].reshape(-1, 1)  # Time

# Define the loss function
def compute_loss(psi_true, psi_pred):
    real_loss = tf.reduce_mean(tf.square(psi_true[:, 0] - psi_pred[:, 0]))
    imag_loss = tf.reduce_mean(tf.square(psi_true[:, 1] - psi_pred[:, 1]))
    total_loss = real_loss + imag_loss
    return total_loss.numpy(), real_loss.numpy(), imag_loss.numpy()

# Make predictions with the PINN model
inputs = tf.concat([x_test, t_test], axis=1)
pinn_predictions = pinn(inputs)

# Extract real and imaginary parts from PINN predictions
pinn_real = pinn_predictions[:, 0].numpy()
pinn_imag = pinn_predictions[:, 1].numpy()

# Make predictions with the NN model
nn_predictions = nn_model.predict(inputs)
nn_real = nn_predictions[:, 0]
nn_imag = nn_predictions[:, 1]

# Compute loss for PINN
pinn_psi_pred = np.hstack([pinn_real.reshape(-1, 1), pinn_imag.reshape(-1, 1)])
pinn_total_loss, pinn_real_loss, pinn_imag_loss = compute_loss(psi_true, pinn_psi_pred)

print(f"PINN Total Loss: {pinn_total_loss}")
print(f"PINN Real Part Loss: {pinn_real_loss}")
print(f"PINN Imaginary Part Loss: {pinn_imag_loss}")

# Compute loss for NN
nn_psi_pred = np.hstack([nn_real.reshape(-1, 1), nn_imag.reshape(-1, 1)])
nn_total_loss, nn_real_loss, nn_imag_loss = compute_loss(psi_true, nn_psi_pred)

print(f"NN Total Loss: {nn_total_loss}")
print(f"NN Real Part Loss: {nn_real_loss}")
print(f"NN Imaginary Part Loss: {nn_imag_loss}")

# Plot Real Part: Ground Truth vs PINN vs NN
plt.figure(figsize=(10, 6))
plt.plot(x_test, psi_true[:, 0], label='True Real Part', color='black', linestyle='dashed')
plt.plot(x_test, pinn_real, label='PINN Real Part', color='blue')
plt.plot(x_test, nn_real, label='NN Real Part', color='red', linestyle='dotted')
plt.xlabel('x')
plt.ylabel('Real(Psi)')
plt.title('Real Part of Psi: Ground Truth vs PINN vs NN')
plt.legend()
plt.grid(True)
plt.show()

# Plot Imaginary Part: Ground Truth vs PINN vs NN
plt.figure(figsize=(10, 6))
plt.plot(x_test, psi_true[:, 1], label='True Imag Part', color='black', linestyle='dashed')
plt.plot(x_test, pinn_imag, label='PINN Imag Part', color='blue')
plt.plot(x_test, nn_imag, label='NN Imag Part', color='red', linestyle='dotted')
plt.xlabel('x')
plt.ylabel('Imag(Psi)')
plt.title('Imaginary Part of Psi: Ground Truth vs PINN vs NN')
plt.legend()
plt.grid(True)
plt.show()

# Print sample predictions
print(f"Sample PINN predictions: {pinn_psi_pred[:5]}")
print(f"Sample ground truth values: {psi_true[:5]}")
